### PR TITLE
Add JDK-23 to the build matrix

### PR DESCRIPTION
**Pull request by reta**
### Description
Add JDK-23 to the build matrix

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/notifications/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
This is for `main` only at the moment (no 2.x backport)

**Review by yuye-aws — APPROVED** [review]

**Comment by yuye-aws** [comment]
@reta Can you check the error from JDK 23: https://github.com/opensearch-project/notifications/actions/runs/11482952177/job/31981106157?pr=977. It shows `Unsupported class file major version 67`.

**Comment by Hailong-am** [comment]
> @reta Can you check the error from JDK 23: https://github.com/opensearch-project/notifications/actions/runs/11482952177/job/31981106157?pr=977. It shows `Unsupported class file major version 67`.

@reta to support java 23, jacoco need upgrade to [0.8.12](https://github.com/jacoco/jacoco/releases/tag/v0.8.12), not sure whether have more libs need to upgrade. 

Also java 23 is not LTS version, we might not rush for supporting this.

**Comment by reta** [comment]
> > @reta Can you check the error from JDK 23: https://github.com/opensearch-project/notifications/actions/runs/11482952177/job/31981106157?pr=977. It shows `Unsupported class file major version 67`.
> 

@yuye-aws will do, thank you

> @reta to support java 23, jacoco need upgrade to [0.8.12](https://github.com/jacoco/jacoco/releases/tag/v0.8.12), not sure whether have more libs need to upgrade.

@Hailong-am I will check thank you 

> Also java 23 is not LTS version, we might not rush for supporting this.

We don't do anything in particular to support it, beside just adding to build / test matrix. The `main` is build with JDK 23 now.

**Comment by reta** [comment]
@yuye-aws @Hailong-am updated outdated deps, should be all set, thanks folks!

**Review by yuye-aws — APPROVED** [review]

**Comment by yuye-aws** [comment]
@reta Can you rebase?

**Comment by reta** [comment]
@yuye-aws mind please taking a look? thank you

**Review by yuye-aws — APPROVED** [review]
LGTM

**Review by Hailong-am — APPROVED** [review]

**Pull request merged**
