### PR TITLE
Adds webhook format check for Chime

### LINKED ISSUE #788: Add Chime webhook URL format check
Add Chime webhook URL format check here
https://github.com/opensearch-project/notifications/blob/main/notifications/notifications/src/main/kotlin/org/opensearch/notifications/index/ConfigIndexingActions.kt#L64

it should have same url format check as Microsoft teams

### PR DESCRIPTION
**Pull request by Noir01**
### Description
Adds webhook format check for Chime

### Issues Resolved
fixes #788 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Noir01** [comment]
Should I add new tests for this like I did in #787 ?

**Comment by Noir01** [comment]
> > Should I add new tests for this like I did in #787 ?
> 
> Yes, please.

Done.

**Review by Hailong-am — APPROVED** [review]

**Comment by eirsep** [comment]
@Noir01  will this be backported to 2.x versions? 
plz let us know so that we can do corresponding backports in alerting plugin too

**Comment by Hailong-am** [comment]
> @Noir01 will this be backported to 2.x versions? plz let us know so that we can do corresponding backports in alerting plugin too

@eirsep Consider the backward capability we are not going to backport to 2.x for coming 2.12 realsee.

**Pull request merged**
