### PR TITLE
Adds webhook format check for Slack

### LINKED ISSUE #787: Add webhook format check for Slack
Add Slack webhook URL format check here 
https://github.com/opensearch-project/notifications/blob/main/notifications/notifications/src/main/kotlin/org/opensearch/notifications/index/ConfigIndexingActions.kt#L59

it should have same url format check as Microsoft teams

### PR DESCRIPTION
**Pull request by Noir01**
### Description
Adds webhook format check for Slack

### Issues Resolved
fixes #787 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zhichao-aws — COMMENTED** [review]
We used mock data to perform integration test. And the mock data may can not pass the new validation. Please also fix the tests in this repo and [dashboards-notifications](https://github.com/opensearch-project/dashboards-notifications).

**Comment by Noir01** [comment]
> We used mock data to perform integration test. And the mock data may can not pass the new validation. Please also fix the tests in this repo and [dashboards-notifications](https://github.com/opensearch-project/dashboards-notifications).

I've (hopefully) fixed the integtests in this repo.
I'll go through dashboard-notifications tests and open a PR there soon

**Comment by Noir01** [comment]
Also, I just noticed the 'Unverified' tags on my commits. I was messing around with the automatic signing off feature and I think I messed up some settings which is leading to all my commits appearing as unverified

**Comment by Hailong-am** [comment]
> Also, I just noticed the 'Unverified' tags on my commits. I was messing around with the automatic signing off feature and I think I messed up some settings which is leading to all my commits appearing as unverified

@Noir01 please follow the guide in https://github.com/opensearch-project/notifications/pull/814/checks?check_run_id=18584633999 to fix DCO and there has a unit test failure, can you fix it as well.

**Comment by Noir01** [comment]
> > Also, I just noticed the 'Unverified' tags on my commits. I was messing around with the automatic signing off feature and I think I messed up some settings which is leading to all my commits appearing as unverified
> 
> @Noir01 please follow the guide in https://github.com/opensearch-project/notifications/pull/814/checks?check_run_id=18584633999 to fix DCO and there has a unit test failure, can you fix it as well.

Can I close this PR and re-open another with the correct signing-off email?

**Comment by Hailong-am** [comment]
> Can I close this PR and re-open another with the correct signing-off email?

You don't have to. Follow the guide mentioned in link https://github.com/opensearch-project/notifications/pull/814/checks?check_run_id=18584633999
1. In your local branch, run: `git rebase HEAD~8 --signoff`
2. Force push your changes to overwrite the branch: `git push --force-with-lease origin patch-2`

**Comment by Noir01** [comment]
I was trying to update this branch, and rebased it, but it got rid of the Verified tag. How can I fix this?

**Comment by Hailong-am** [comment]
> I was trying to update this branch, and rebased it, but it got rid of the Verified tag. How can I fix this? Also, how do I deal with the failed codecov tests?

The DCO failed with reason 
> Summary
Commit sha: [7e6b4cd](https://github.com/opensearch-project/notifications/pull/814/commits/7e6b4cd8c5dfcac3bb5913e0b617d424d023504d), Author: Aniruddh, Committer: Aniruddh; Can not find "Aniruddh [63553175+noir01@users.noreply.github.com](mailto:63553175+noir01@users.noreply.github.com)", in ["Aniruddh Srivastava [ansriv2005@gmail.com](mailto:ansriv2005@gmail.com)", "Aniruddh Srivastava [aniruddh@purdue.edu](mailto:aniruddh@purdue.edu)"].
Commit sha: [0791276](https://github.com/opensearch-project/notifications/pull/814/commits/0791276af41ce0ad72bc77a54ea9a2422f776ce3), Author: Aniruddh Srivastava, Committer: Aniruddh; Expected "Aniruddh Srivastava [ansriv2005@gmail.com](mailto:ansriv2005@gmail.com)", but got "Aniruddh Srivastava [aniruddh@purdue.edu](mailto:aniruddh@purdue.edu)".

1. can you check the email settings of your account https://github.com/settings/emails make sure `Keep my email addresses private` is not checked.
2. make sure you local git config user email is `ansriv2005@gmail.com` with command `git config user.email`

**Comment by Noir01** [comment]
> > I was trying to update this branch, and rebased it, but it got rid of the Verified tag. How can I fix this? Also, how do I deal with the failed codecov tests?
> 
> The DCO failed with reason
> 
> > Summary
> > Commit sha: [7e6b4cd](https://github.com/opensearch-project/notifications/pull/814/commits/7e6b4cd8c5dfcac3bb5913e0b617d424d023504d), Author: Aniruddh, Committer: Aniruddh; Can not find "Aniruddh [63553175+noir01@users.noreply.github.com](mailto:63553175+noir01@users.noreply.github.com)", in ["Aniruddh Srivastava [ansriv2005@gmail.com](mailto:ansriv2005@gmail.com)", "Aniruddh Srivastava [aniruddh@purdue.edu](mailto:aniruddh@purdue.edu)"].
> > Commit sha: [0791276](https://github.com/opensearch-project/notifications/pull/814/commits/0791276af41ce0ad72bc77a54ea9a2422f776ce3), Author: Aniruddh Srivastava, Committer: Aniruddh; Expected "Aniruddh Srivastava [ansriv2005@gmail.com](mailto:ansriv2005@gmail.com)", but got "Aniruddh Srivastava [aniruddh@purdue.edu](mailto:aniruddh@purdue.edu)".
> 
> 1. can you check the email settings of your account https://github.com/settings/emails make sure `Keep my email addresses private` is not checked.
> 2. make sure you local git config user email is `ansriv2005@gmail.com` with command `git config user.email`

I just did both of those steps

**Comment by Hailong-am** [comment]
> I just did both of those steps

@Noir01  after this, please follow the steps in https://github.com/opensearch-project/notifications/pull/814/checks?check_run_id=18694631981 to fix DCO

**Review by zhichao-aws — COMMENTED** [review]
Good work, but I think we should add more tests cases. Can we add unit test cases to test more success cases and fail cases for url validation? And the integ test case for exception message?

**Comment by Noir01** [comment]
> Good work, but I think we should add more tests cases. Can we add unit test cases to test more success cases and fail cases for url validation? And the integ test case for exception message?

I'm not very experienced in this, so could you explain a bit more?

**Comment by zhichao-aws** [comment]
> > Good work, but I think we should add more tests cases. Can we add unit test cases to test more success cases and fail cases for url validation? And the integ test case for exception message?
> 
> I'm not very experienced in this, so could you explain a bit more?

Please refer to these test cases: https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/notifications/index/ConfigIndexingActionsTests.kt#L17; https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/MicrosoftTeamsNotificationConfigCrudIT.kt#L132

**Comment by Noir01** [comment]
> > > Good work, but I think we should add more tests cases. Can we add unit test cases to test more success cases and fail cases for url validation? And the integ test case for exception message?
> > 
> > 
> > I'm not very experienced in this, so could you explain a bit more?
> 
> Please refer to these test cases:
> 
> https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/notifications/index/ConfigIndexingActionsTests.kt#L17
> 
> ;
> https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/MicrosoftTeamsNotificationConfigCrudIT.kt#L132

Got it. Do you only want those two copied for slack?

**Comment by zhichao-aws** [comment]
> > > > Good work, but I think we should add more tests cases. Can we add unit test cases to test more success cases and fail cases for url validation? And the integ test case for exception message?
> > > 
> > > 
> > > I'm not very experienced in this, so could you explain a bit more?
> > 
> > 
> > Please refer to these test cases:
> > https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/notifications/index/ConfigIndexingActionsTests.kt#L17
> > 
> > ;
> > https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/MicrosoftTeamsNotificationConfigCrudIT.kt#L132
> 
> Got it. Do you only want those two copied for slack?

You know we're adding tests to make sure the code behavior are as expected. And here we want to make sure the url check reject wrong url, and return correct message to help users fix it. You can write test cases just like this example, but I think you should modify these mock urls to adapt to you regex expression

**Comment by Noir01** [comment]
> > > > > Good work, but I think we should add more tests cases. Can we add unit test cases to test more success cases and fail cases for url validation? And the integ test case for exception message?
> > > > 
> > > > 
> > > > I'm not very experienced in this, so could you explain a bit more?
> > > 
> > > 
> > > Please refer to these test cases:
> > > https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/notifications/index/ConfigIndexingActionsTests.kt#L17
> > > 
> > > ;
> > > https://github.com/opensearch-project/notifications/blob/62b7b4f840e7e224f947f1745da375df6f419b9b/notifications/notifications/src/test/kotlin/org/opensearch/integtest/config/MicrosoftTeamsNotificationConfigCrudIT.kt#L132
> > 
> > 
> > Got it. Do you only want those two copied for slack?
> 
> You know we're adding tests to make sure the code behavior are as expected. And here we want to make sure the url check reject wrong url, and return correct message to help users fix it. You can write test cases just like this example, but I think you should modify these mock urls to adapt to you regex expression

Oh yeah, of course.

**Comment by Noir01** [comment]
> Good work, but I think we should add more tests cases. Can we add unit test cases to test more success cases and fail cases for url validation? And the integ test case for exception message?

Done.

**Comment by Hailong-am** [comment]
The validation happens when create new slack channel or update existing slack channel. To be compatible with existing data, we may want to add a condition for update case, only if webhook url has changed, we do the validation. we can have this in follow up PR and remove the `backport 2.x` label for now.

**Review by Hailong-am — APPROVED** [review]

**Review by zhichao-aws — APPROVED** [review]
lgtm

**Comment by Hailong-am** [comment]
> > The validation happens when create new slack channel or update existing slack channel. To be compatible with existing data, we may want to add a condition for update case, only if webhook url has changed, we do the validation. we can have this in follow up PR and remove the `backport 2.x` label for now.
> 
> @Hailong-am Shall I open a new issue for this?

sure, thanks

**Comment by zhichao-aws** [comment]
> > > The validation happens when create new slack channel or update existing slack channel. To be compatible with existing data, we may want to add a condition for update case, only if webhook url has changed, we do the validation. we can have this in follow up PR and remove the `backport 2.x` label for now.
> > 
> > 
> > @Hailong-am Shall I open a new issue for this?
> 
> sure, thanks

We already have these issues now #818 #819 .

**Pull request merged**
