### PR TITLE
[Build] add common to tsconfig

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Need to include common to be compiled down with the release
artifact

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
https://github.com/opensearch-project/notifications/issues/410
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by qreshi** [comment]
@kavilla Was this always a requirement? Dashboards didn't fail to come up when I was testing Notifications locally. How can we reproduce is on our side in the future to avoid catching at the time of the full distribution build?

**Comment by kavilla** [comment]
@qreshi yeah it would be acceptable with TypeScript files but when we compile down the files when producing a release artifact we have to tell the compiler to include these files.

**Comment by qreshi** [comment]
Looks like since `common` was missing from the produced artifact it wouldn't be caught unless the built artifact was used to test with.

This can probably be added to the GitHub Actions workflow later so it uses the built artifact to test with.

**Review by qreshi — APPROVED** [review]

**Comment by qreshi** [comment]
Created an issue for tracking the above: https://github.com/opensearch-project/notifications/issues/412

**Review by praveensameneni — APPROVED** [review]

**Pull request merged**
