### PR TITLE
upgrade upload-artifact to version 4

### PR DESCRIPTION
**Pull request by Hailong-am**
### Description
upgrade upload-artifact to version 4, as v1 and v2 are deprecated.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/notifications/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by yuye-aws** [comment]
Looks good to me. Will approve when the CI passed.

**Comment by yuye-aws** [comment]
Can u check the CI error?

**Comment by Hailong-am** [comment]
failed ones are caused BWC, we can ignore.

**Review by yuye-aws — APPROVED** [review]

**Comment by Hailong-am** [comment]
close it due to #961

**Pull request closed without merging**
