### PR TITLE
add release notes for 2.5

### PR DESCRIPTION
**Pull request by ansjcy**
Signed-off-by: Chenyang Ji <cyji@amazon.com>

### Description
2.5 release notes for notification

### Issues Resolved
https://github.com/opensearch-project/notifications/issues/588

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by praveensameneni — APPROVED** [review]

**Comment by qreshi** [comment]
Let's add the following PRs to the release notes as they are part of 2.5. I think they are all related to testing so we can put them under the **Infrastructure** category based on the [OpenSearch release notes formatting](https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md):

* https://github.com/opensearch-project/notifications/pull/566
* https://github.com/opensearch-project/notifications/pull/574
* https://github.com/opensearch-project/notifications/pull/590
* https://github.com/opensearch-project/notifications/pull/587

**Comment by ansjcy** [comment]
> Let's add the following PRs to the release notes as they are part of 2.5. I think they are all related to testing so we can put them under the **Infrastructure** category based on the [OpenSearch release notes formatting](https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md):
> 
> * [Fix time bounds in query to address indeterminism #566](https://github.com/opensearch-project/notifications/pull/566)
> * [Reduce Cypress test flakiness #574](https://github.com/opensearch-project/notifications/pull/574)
> * [Add index refresh after config creation and deletion in integration tests #590](https://github.com/opensearch-project/notifications/pull/590)
> * [Add BWC tests for running against distribution bundle #587](https://github.com/opensearch-project/notifications/pull/587)

But I saw them already included in the [2.4 release](https://github.com/opensearch-project/notifications/commits/2.4), should I add them anyway?

**Comment by qreshi** [comment]
@ansjcy They were all backported to 2.4's branch it seems but it was after 2.4.0 released. I suppose that's your call to make then. I usually try to add them in the first release that has a change and will usually exclude them if it's a backport from a newer released version after that.

**Comment by qreshi** [comment]
@zelinh It looks like all the backend CI runs are failing because of the BWC task, do you know if this related to the recent changes?

**Review by qreshi — APPROVED** [review]

**Review by bowenlan-amzn — APPROVED** [review]

**Pull request merged**
