### PR TITLE
Feature support microsoft teams webhooks

### PR DESCRIPTION
**Pull request by dankyalo599**
### Description
[FEATURE] Support Microsoft Teams webhooks

### Issues Resolved
t Supports posting to MSTeams channel through incoming webhook connector to a new channel

### Check List
- [X ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by lezzago** [comment]
@dankyalo599, can you please add examples of the telegram and microsoft teams webhooks working successfully? Additionally, please rename the PR to support microsoft teams and telegram.

**Comment by dankyalo599** [comment]
on it

**Comment by zhichao-aws** [comment]
This PR is included in [#608](https://github.com/opensearch-project/notifications/pull/608/commits), can be closed

**Comment by zhichao-aws** [comment]
stale PR of #638 ,close it

**Pull request closed without merging**
