### PR TITLE
Remove scripts from notifications repo due to naming of the entries in manifest file

### LINKED ISSUE #379: Add support for build version qualifiers.
Coming from https://github.com/opensearch-project/opensearch-build/issues/1632, add support for `-Dbuild.version_qualifier=`. 

The distribution build process now supports passing additional optional qualifiers other than the 3 digit versions, e.g. `2.0.0-alpha1`. Add the ability to pass additional qualifier to build scripts, and generate artifacts with a version that includes the qualifier.

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Remove scripts from notifications repo due to naming of the entries in manifest file
 
### Issues Resolved
#379
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
This will go in parallel with https://github.com/opensearch-project/opensearch-build/pull/1957

**Comment by peterzhuamazon** [comment]
Make change to remove the scripts from notifications repo due to the manifest `name` field cannot matching the repo name of notifications due to `notifications-core` and `notifications-notifications` subfolder structure.

**Comment by rishabhmaurya** [comment]
copying artifacts part can go in a gradle task which can be defined in the parent project of notification plugin and would keep things cleaner. 
Approving it now and this can be cleaned up later!

**Review by praveensameneni — APPROVED** [review]

**Review by getsaurabh02 — APPROVED** [review]

**Review by tianleh — APPROVED** [review]

**Review by CEHENKLE — APPROVED** [review]

**Comment by dblock** [comment]
@rishabhmaurya Where can I read more about how notifications-core came to be, and why isn't it in its own repo? There are multiple hacks that were required to make it part of the distribution, starting with https://github.com/opensearch-project/opensearch-build/pull/1959, and I suspect there will be more interesting hacks downstream when we get to publishing these to maven, or try to implement some other feature.

**Pull request merged**
