### PR TITLE
Remove features and feature_list usage in Notifications

### PR DESCRIPTION
**Pull request by qreshi**
### Description
* Updates Kotlin to 1.6.10 (this was to be consistent with common-utils and caused compilation errors which were also fixed in this PR)
* Removes feature and feature_list usage in backend and frontend

This PR is making changes to integrate the changes in https://github.com/opensearch-project/common-utils/pull/136

**Note**: During manual testing on the frontend it became apparent that the frontend is incorrectly forming an Email channel object (the recipient is a list of Strings instead of list of EmailRecipient objects i.e `{ "recipient": "email@test.com" }` like the backend expects). We may favor the frontend format here since wrapping it in an object seems unnecessary. In either case, this will be addressed in a follow-up PR.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by qreshi** [comment]
Also since the GitHub Actions for building the backend is still failing (since common-utils 2.0 snapshot is not available yet) I ran the build locally which passed:

```
notifications % ./gradlew build
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.3
  OS Info               : Mac OS X 10.16 (x86_64)
  JDK Version           : 14 (OpenJDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home
  Random Testing Seed   : 2F8DD9510DED255E
  In FIPS 140 mode      : false
=======================================

BUILD SUCCESSFUL in 5m 42s
55 actionable tasks: 13 executed, 42 up-to-date
```

**Comment by dbbaughe** [comment]
> opensearch-project/common-utils#136

What is the hold up for having the 2.0 snapshot published for common utils?

**Comment by qreshi** [comment]
> What is the hold up for having the 2.0 snapshot published for common utils?

I think from the recent plugins that were added to the 2.0 build manifest, first it was Job Scheduler (which was fixed), then it seems that Alerting was added prematurely and was failing it because it wasn't upgraded to 2.0. That was the state of things last I checked.

**Review by dbbaughe — APPROVED** [review]
LGTM, up to you if you want to wait for common utils 2.0 snapshot to get published.

**Review by aditjind — APPROVED** [review]

**Comment by qreshi** [comment]
I see the common-utils 2.0 snapshot is available now. The backend test workflow is failing on some flaky tests that doesn't seems to be difficult to reproduce locally. I'll merge this change in for now and look at fixing the flaky tests in a follow-up PR.

**Pull request merged**
