### PR TITLE
Change Copyrights in NOTICE

### PR DESCRIPTION
**Pull request by kavithacm**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by davidcui1225 — COMMENTED** [review]
Please update the README as well. Reference PR: https://github.com/opensearch-project/dashboards-reports/pull/220/files. Also the branch name is `dco-workflow`?

**Comment by kavithacm** [comment]
> Please update the README as well. Reference PR: https://github.com/opensearch-project/dashboards-reports/pull/220/files. Also the branch name is `dco-workflow`?
I'm just reusing the same branch i created for editing dco workflow. 
I'll update the README too

**Comment by davidcui1225** [comment]
> > Please update the README as well. Reference PR: https://github.com/opensearch-project/dashboards-reports/pull/220/files. Also the branch name is `dco-workflow`?
> > I'm just reusing the same branch i created for editing dco workflow.
> > I'll update the README too

Generally we don't want to re-use branches for separate issues. In the future, after a PR is merged please delete the branch and then cut a new one from `main` after fetching and merging from upstream.

**Comment by kavithacm** [comment]
> > > Please update the README as well. Reference PR: https://github.com/opensearch-project/dashboards-reports/pull/220/files. Also the branch name is `dco-workflow`?
> > > I'm just reusing the same branch i created for editing dco workflow.
> > > I'll update the README too
> 
> Generally we don't want to re-use branches for separate issues. In the future, after a PR is merged please delete the branch and then cut a new one from `main` after fetching and merging from upstream.

Yeah okay. I'll do that

**Review by joshuali925 — APPROVED** [review]

**Pull request merged**
