### PR TITLE
Update Gradle to 8.10.2

### PR DESCRIPTION
**Pull request by reta**
### Description
Update Gradle to 8.10.2

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/notifications/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by yuye-aws** [comment]
@reta Can you provide more context on why are we upgrading gradle?

**Comment by reta** [comment]
> @reta Can you provide more context on why are we upgrading gradle?

Thanks for looking @yuye-aws , there are at least 2 reasons:
 - support builds under JDK-23 (which `main` is already on)
 - keeping build tooling up to date

**Review by Hailong-am — APPROVED** [review]

**Comment by yuye-aws** [comment]
@reta Thanks for providing the context. Seems there are flakey tests now. Rerunning the CI now...

**Comment by yuye-aws** [comment]
> * support builds under JDK-23 (which `main` is already on)

Is there going to be a JDK upgrade PR towards 23?

**Comment by reta** [comment]
> Is there going to be a JDK upgrade PR towards 23?

Yes, I didn't do it there since backport to 2.x will fail

**Review by yuye-aws — APPROVED** [review]
The code looks good to me. CI fails due to flakey test on cluster health

**Pull request merged**
